on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  package:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Make sure to be possible to create package
        run: npm run package

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: blueberry-brackets-dark-theme.vsix

  azure:
    runs-on: ubuntu-24.04
    needs: [package]
    name: Release in Azure Marketplace
    if: startsWith(github.ref, 'refs/tags/') && github.event_name != 'pull_request'
    timeout-minutes: 15
    env:
      VSCE_PAT: '${{ secrets.VSCE_PAT }}'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download artifact
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh run download
          tree

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - run: npm run publish

  github:
    runs-on: ubuntu-24.04
    needs: [package]
    name: Release in GitHub
    if: startsWith(github.ref, 'refs/tags/') && github.event_name != 'pull_request'
    timeout-minutes: 15
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      # Required to checkout for gh command
      - uses: actions/checkout@v4
      - name: Download artifact
        run: |
          gh run download
          tree
      - run: |
          gh release create --verify-tag "$GITHUB_REF_NAME" --title "$GITHUB_REF_NAME" packages/blueberry-brackets-dark-theme.vsix
